/*
 * DeviceDefine.h
 *
 *  Created on: 2018年10月19日
 *      Author: queen
 */

#ifndef DEFINE_DEVICEDEFINE_H_
#define DEFINE_DEVICEDEFINE_H_

//设备类型
typedef enum _DP_DEV_TYPE_E {
DP_DEV_TYPE_PCSOTF = 0x0001,				//PC管理软件
DP_DEV_TYPE_SSERVER,					//流媒体服务器
DP_DEV_TYPE_ESOFT,						//工程软件
DP_DEV_TYPE_IDMS4K_INPUT,				//输入节点
DP_DEV_TYPE_IDMS4K_OUTPUT,				//输出节点
DP_DEV_TYPE_BUTT,
}DP_DEV_TYPE_E;

//设备型号
typedef enum _DP_DEV_NUM_E{
DP_DEV_NUM_H1I4K = 0x1001,				// 1通道HDMI 4K输入板
DP_DEV_NUM_H1O4K,						// 1通道HDMI 4K输出板
DP_DEV_NUM_BUTT,
} DP_DEV_NUM_E;

//设备工作模式
typedef enum _DP_DEV_WORK_MODE_E {
DP_DEV_WORK_MODE_MATRIX = 0x2001,		//矩阵模式
DP_DEV_WORK_MODE_MONTAGE,			//拼接屏模式
DP_DEV_WORK_MODE_KVM,				// KVM模式
DP_DEV_WORK_MODE_BUTT,
} DP_DEV_WORK_MODE_E;

//设备运行状态
typedef enum _DP_DEV_RUNNING_STATE_E {
DP_DEV_RUNNING_STATE_INITIALIZED = 0x3001,	//初始化
DP_DEV_RUNNING_STATE_NOT_CONFIG,			//未配置
DP_DEV_RUNNING_STATE_NOT_CONNECT,			//未入网
DP_DEV_RUNNING_STATE_ABNORMAL,				//运行异常
DP_DEV_RUNNING_STATE_NORMAL,				//运行正常
DP_DEV_RUNNING_STATE_SYNCHING,				//同步中
DP_DEV_RUNNING_STATE_UPGRADING,				//升级中
DP_DEV_RUNNING_STATE_CLOSING,				//关闭中
DP_DEV_RUNNING_STATE_BUTT,
} DP_DEV_RUNNING_STATE_E;

//工作状态
typedef enum _DP_DEV_WORK_STATE_E {
DP_DEV_WORK_STATE_FREE=0x4001,			//空闲
DP_DEV_WORK_STATE_LOGON,				//用户登录使用中
DP_DEV_WORK_STATE_CONTROL,				//控制中
DP_DEV_WORK_STATE_VIDEO,				//视频中
DP_DEV_WORK_STATE_BEMONOPOLIZED,		//被独占
DP_DEV_WORK_STATE_BEPOSITIVECONTORL,	//被控制
DP_DEV_WORK_STATE_BEONLYVIDEO,			//被视频
DP_DEV_WORK_STATE_BEMULTI,				//被复用
DP_DEV_WORK_STATE_BUTT,
} DP_DEV_WORK_STATE_E;

#endif /* DEFINE_DEVICEDEFINE_H_ */
